export default {
    // 登录
    'login': '/admin/login',
    // 登出
    'logout': '/admin/logout',
    // 获取账号信息
    'getAccounts': '/admin/accounts',
    // 获取后台姓名和学号
    'getLoginAccount': '/admin/get-student-name',
    // 添加账号
    'addAccount': '/admin/accounts/create-account',
    // 重置密码
    'resetPasswd': '/admin/accounts/resetting',
    // 修改信息
    'modifyInfo': '/admin/accounts/modify-info',
    // 降级为学生账号
    'degrade': '/admin/accounts/demote',
    // 删除账号
    'deleteAccount': '/admin/accounts/delete',
    // 学生账号管理-添加账号
    'studentsAdd': '/admin/students/create-students',
    // 学生账号管理-重置密码
    'studentResetting': '/admin/students/resetting',
    // 学生账号管理-删除账号
    'studentsDelete': '/admin/students/delete',
    // 学生账号管理-锁定账号
    'studentsLock': '/admin/students/lock-students',
    // 学生账号管理-修改信息
    'studentsAlter': '/admin/students/alter-students',
    // 学生账号管理
    'getStudents': '/admin/students',
    // 学生账号管理-班级管理
    'studentsMonitor': '/admin/students/monitor',
    // 学生账号管理-班级管理-添加班级
    'addClass': '/admin/students/monitor/create',
    // 学生账号管理-班级管理-修改班长
    'alterClass': '/admin/students/monitor/alter',
    // 学生账号管理-班级管理-删除班长
    'deleteClass': '/admin/students/monitor/delete'
}
