export default {
    // 后台
    // 获取类型名
    'getQuestionTypes': '/admin/get-question-types',
    // 获取问题列表
    'getQuestions': '/admin/get-questions',
    // 搜索问题
    'searchQuestions': '/admin/search-questions',
    // 问题置顶
    'getPinnedQuestions': '/admin/get-pinned-questions',
    // 删除问题
    'deleteQuestion': '/admin/delete-question',
    // 锁定问题
    'lockQuestion': '/admin/lock-question',
    // 获取查看的问题信息
    'getCheckQuestions': '/admin/get-check-questions',
    // 获取回答问题的列表
    'getSolutions': '/admin/get-solutions',
    // 删除回答
    'deleteSolution': '/admin/delete-solution',
    // 采纳为最佳
    'adoptAsBest': '/admin/adopt-as-best',
    // 给回答点赞
    'likes': '/admin/likes',
    // 给回答点踩
    'dislikes': '/admin/dislikes',
    // 发布回答
    'publishAnswer': '/admin/publish-answers',
    // 添加类型
    'addType': '/admin/add-type',
    // 问答系统设置
    'setQuestionAndAnswer': '/admin/set-question-and-answer'
}
